machine: "ks" # [g3, ks]
train:
  root:
  resume_path_decoder: "/data/phd/jinjiachun/experiment/decoder/0621_decoder_dim_down_32/Decoder-decoder-95k"
  skipped_keys:
  resume_path_recloss: "/data/phd/jinjiachun/experiment/decoder/0621_decoder_dim_down_32/Loss-decoder-95k"
  global_step: 95000

  exp_name: &exp_name "decoder"
  wandb_proj: *exp_name
  output_dir: "0621_decoder_dim_down_32"
  logging_dir: "logs"
  mixed_precision: "bf16"
  gradient_accumulation_steps: 1
  report_to: "wandb"

  lr: 1e-4
  lr_disc: 1e-5
  num_iter: 200000
  save_every: 5000

decoder:
  type: "vit_pixel_decoder"
  hidden_size: 1024
  depth: 28
  num_heads: 16
  patch_size: 16
  grid_size: 24
  input_dim: 32 # new
  siglip_feature_dim: 1024 # new
  siglip_feature_dim_down: 32 # new

rec_loss:
  perceptual_loss_name: "lpips-convnext_s-1.0-0.1"
  rec_weight: 1.0
  perceptual_weight: 1.1
  discriminator_weight: 0.1
  lecam_regularization_weight: 0.001

  discriminator_factor: 1.0
  discriminator_start_iter: 0

data:
  name: "imagenet_wds"
  train_path:
  siglip_preprocess: false
  batch_size: 40
  num_workers: 0
  img_size: 384