machine: "ks" # [g3, ks]
train:
  root:
  resume_path_decoder: "/data/phd/jinjiachun/experiment/decoder/0619_decoder/Decoder-decoder-425k"
  skipped_keys:
  resume_path_recloss: "/data/phd/jinjiachun/experiment/decoder/0619_decoder/Loss-decoder-425k"
  global_step: 425000

  exp_name: &exp_name "decoder"
  wandb_proj: *exp_name
  output_dir: "0619_decoder"
  logging_dir: "logs"
  mixed_precision: "bf16"
  gradient_accumulation_steps: 1
  report_to: "wandb"

  lr: 1e-4
  lr_disc: 1e-5
  num_iter: 500000
  save_every: 5000

decoder:
  type: "vit_pixel_decoder"
  hidden_size: 1024
  depth: 24
  num_heads: 16
  patch_size: 16
  grid_size: 24
  input_dim: 1024

rec_loss:
  perceptual_loss_name: "lpips-convnext_s-1.0-0.1"
  rec_weight: 1.0
  perceptual_weight: 1.1
  discriminator_weight: 0.1
  lecam_regularization_weight: 0.001

  discriminator_factor: 1.0
  discriminator_start_iter: 0

data:
  name: "imagenet_wds"
  train_path:
  siglip_preprocess: false
  batch_size: 45
  num_workers: 0
  img_size: 384